/* eslint-disable */
/**
 * this file is auto generated by umi,
 * don't modify it!!!
 */
import BatchImportExport from '@hosoft/hos-plugin-batch-import-export/admin/plugin-index.js'
import DocGen from '@hosoft/hos-plugin-doc-gen/admin/plugin-index.js'
import Payment from '@hosoft/hos-plugin-payment/admin/plugin-index.js'
import SdkGen from '@hosoft/hos-plugin-sdk-gen/admin/plugin-index.js'
import Social from '@hosoft/hos-plugin-social/admin/plugin-index.js'

const pluginList = []

pluginList.push({ instance: BatchImportExport, name: 'hos-plugin-batch-import-export', type: 'manager', dir: '@hosoft/hos-plugin-batch-import-export/admin/plugin-index.js', version: '1.0.0', dis_name: 'HoServer plugin for batch import / export model data' })
pluginList.push({ instance: DocGen, name: 'hos-plugin-doc-gen', type: 'manager', dir: '@hosoft/hos-plugin-doc-gen/admin/plugin-index.js', version: '1.0.0', dis_name: 'HoServer plugin for auto generate api document' })
pluginList.push({ instance: Payment, name: 'hos-plugin-payment', type: 'manager', dir: '@hosoft/hos-plugin-payment/admin/plugin-index.js', version: '1.0.0', dis_name: 'HoServer plugin support server integration with common used payment services' })
pluginList.push({ instance: SdkGen, name: 'hos-plugin-sdk-gen', type: 'manager', dir: '@hosoft/hos-plugin-sdk-gen/admin/plugin-index.js', version: '1.0.0', dis_name: 'HoServer plugin for auto generate api client SDK files of common languages' })
pluginList.push({ instance: Social, name: 'hos-plugin-social', type: 'manager', dir: '@hosoft/hos-plugin-social/admin/plugin-index.js', version: '1.0.0', dis_name: 'HoServer social login plugin' })

export default pluginList